app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
